-- MySQL Script generated by MySQL Workbench
-- Fri Oct 23 23:22:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Categorie` (
  `idCategorie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomCategorie` VARCHAR(45) NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Produit` (
  `idProduit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomProduit` VARCHAR(45) NULL,
  `prix` INT NULL,
  `description` TINYTEXT NULL,
  `quantite` INT NULL,
  `photos` VARCHAR(45) NULL,
  `Categorie_idCategorie` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProduit`),
  INDEX `fk_Produit_Categorie_idx` (`Categorie_idCategorie` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Client` (
  `idClient` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NOT NULL,
  `passwrd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Commande` (
  `idCommande` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dateCommande` DATE NULL,
  `Client_idClient` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Commande_Client1_idx` (`Client_idClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Pagnier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Pagnier` (
  `idPagnier` INT NOT NULL AUTO_INCREMENT,
  `nomPagnier` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagnier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`LigneCommande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`LigneCommande` (
  `Produit_idProduit` INT UNSIGNED NOT NULL,
  `Commande_idCommande` INT UNSIGNED NOT NULL,
  `quantite` INT UNSIGNED NOT NULL,
  `prix` INT UNSIGNED NOT NULL,
  `Pagnier_idPagnier` INT NOT NULL,
  PRIMARY KEY (`Produit_idProduit`, `Commande_idCommande`),
  INDEX `fk_Produit_has_Commande_Commande1_idx` (`Commande_idCommande` ASC) VISIBLE,
  INDEX `fk_Produit_has_Commande_Produit1_idx` (`Produit_idProduit` ASC) VISIBLE,
  INDEX `fk_LigneCommande_Pagnier1_idx` (`Pagnier_idPagnier` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
